server:
  port: 9002

spring:
  application:
    name: Kafka-Producer
  h2:
    console:
      enabled: true
    database:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password:
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
kafka:
  bootstrap-servers: localhost:9092
  topic-name: customer_details
